# The database vendor.
db=postgres

# The username of the database user.
db-username=keycloak

# The password of the database user.
db-password=keycloak-strongPassword

# Sets the hostname of the default JDBC URL of the chosen vendor
db-url-host=database-keycloak

db-url-database=keycloak-users