quarkus:
    http:
        host: 0.0.0.0
        port: 8888
        # --- HTTP Authentication Rules ---
        auth:
            permission:
                # Règle 1 : Protéger uniquement les routes de l'API
                api:
                    paths: /api/*
                    policy: authenticated
                # Règle 2 : Laisser tout le reste public (index.html, Swagger, etc.)
                public:
                    paths:
                        - /*
                        - /q/swagger-ui/*
                        - /q/openapi
                    policy: permit
        # --- CORS Configuration ---
        cors:
            enabled: true
            exposed-headers:
                - location
                - info
            access-control-max-age: 24H
            origins:
                - http://localhost
                - http://localhost:8888
                - http://localhost:8180
            methods:
                - GET
                - PUT
                - POST
                - DELETE
                - OPTIONS
            headers:
                - Authorization
                - Content-Type
                - Accept
    # --- OIDC (OpenID Connect) Configuration ---
    oidc:
        auth-server-url: http://localhost:8180/realms/usager
        client-id: backend
        credentials:
            secret: ENC[AES256_GCM,data:/daltYcxB21pgCWL9b+Wd01mfCSOTMA4cx4MujYF/j2VZ7e9,iv:JDop/i4L3CZWJnqaz/VmdpqMAONz9+9BJ2xmccrqbZI=,tag:Fe99xj/qEq50Hqa+9Z1rHw==,type:str]
        application-type: service
    # --- Data Source Configuration ---
    datasource:
        devservices:
            enabled: false
        db-kind: postgresql
        username: ENC[AES256_GCM,data:Spv9fHNMlZo=,iv:4Z3z/wiM1GTrIg0Z0hS2P3arsEKSzkLAWV8/Je67PgA=,tag:RPWfiOgMKO6JJ+d0kQQaHw==,type:str]
        password: ENC[AES256_GCM,data:mhTLET7bulg=,iv:uUWTWjlyG3xHU1oPcVuJZEWLHdOxXHLWzPTApxzm3UY=,tag:C5i/lVDnQw+hSTnh6qF2DQ==,type:str]
        jdbc:
            url: jdbc:postgresql://localhost:5444/postgres
            leak-detection-interval: 5M
    # --- MyBatis Mapping Configuration ---
    mybatis:
        xmlconfig:
            enable: false
        map-underscore-to-camel-case: true
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUjg1Skp5VWhXVlBXQmNt
            VlFSN3kwZHUvdk9XTnowQjAyUUIzY0R4bEhFCnRROXJqMzVxOEpXcWpFd0p2OEpw
            Vmk0amNqOE5WODN0Nnh2R0xoQTVHVXcKLS0tIEJRRWtkQmx6eGYyUDdKWmM3OGNZ
            WGhZU0RyTTVucThjck1rQ01hNVBMekkK4gyN4OahYtf2Qda98KtwiPstrMoloP0C
            rv4vz9wbxgz+6na6Q5zIo0SarDG2RROxIKzn20tGYUwvUWbH23WK2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e3t3m9vs9fyreact9jvy4qry2n9qgz9k629hnnsun2r8lrd0g54s03h9h6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcFFidHRJZkNaTHB0cksv
            VzZ4TjBlMldMbmdoUEZrNjZBZGNMdjNIK0NrCnJ0ZWVrRWdQdUZuemsyR0RTMUND
            bVpjMTdRcWZjRUIyekZ1Z1dHL2tXRDAKLS0tIC9zOFJIVGwzRGE5VDRiNENzS01q
            cUc3N011cXJENVBHYkYzMEpvRXg4Y00KPgNcJdagdnvHJlIYYYp4eNeIn1DMyBXz
            nz1kZpNxBLIyDLfNE7qgCwbMz0OvY/0oTG0mkYHZw6XSdyJ93JMk5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ujfummyn2rxcrnfqt5fkrazunewre2erru62m6llavetzwlwzgwqnduhku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUTVCMWZ5dEh6SmxSbTUz
            SkhGT2xHM1ZMMmJTaURNVnordmh1UDkwS1ZrCmRXd1MzNXljUmpwMmlHQkV6eXNl
            eFZJTUxJOEJiSEJ5VDREMGRaNnVtR0UKLS0tIGFLUWdqVmM4NklvMXpJRlBkVVBu
            czVCM0xFVytZWjg5MDRaRG5PVTROckUKm098KI4bJXKjEJtOMMnk9Y+Y7yx6Z7kD
            EG2iH//iR6vHd2r9j9939Hy2vpLdZemHeujhAf1n9tS5WWV5hHtw9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g6untvsuz98h7v5xmstlwhhd8zrr0zac4qlpu0d4x9tjf8dqeytqyut0vc
    encrypted_regex: ^(data|stringData|password|client_id|client_secret|secret|username|name)$
    lastmodified: "2026-06-09T17:19:25Z"
    mac: ENC[AES256_GCM,data:XIek17WRUlZO/qvcr8/of0TpuQmQRCmxCtsABWA7x3kLcjZKslAyIWzPAPKLRJzCLWk9gaDa5/awNjPDHl7MpEJzZajL4IHiUHeukppDHKFA+Knf8r1KBWhQyEkF8ly1a3oLvpGpCfu9ZvTEXR1r39wSAPRDEwKb/GnAHHI7+7M=,iv:3sL+uHCb08s/POt19JedY96qhj2xu5pvwUwiC2Bxpag=,tag:Xh+verfl6ijbKjE85FzYFA==,type:str]
    version: 3.13.1
