@base_ = {{base_url}}/api/utilisateur

#Variables pour les prochaines requêtes
@cip =
@pseudo =
@courriel=
@nom=
@prenom=

### getUtilisateurs
GET {{base_}}
    ?cip={{cip}}
    &pseudo={{pseudo}}
    &courriel={{courriel}}
    &nom={{nom}}
    &prenom={{prenom}}
Authorization: Bearer {{auth_token}}

### getUtilisateur
GET {{base_}}/get
    ?cip={{cip}}
    &pseudo={{pseudo}}
    &courriel={{courriel}}
    Content-Type: *application/json
Authorization: Bearer {{auth_token}}


### deleteUtilisateur
@delUser = test
DELETE {{base_}}/{{delUser}}
Authorization: Bearer {{auth_token}}


### ajouteContacte
@cip_adder = tura2517
@cip_contact = belx8646
POST {{base_}}/
    {{cip_adder}}/
    contact/
    {{cip_contact}}
Authorization: Bearer {{auth_token}}
