events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log off;
    log_not_found off;
    error_log /var/log/nginx/error.log error;

    server {
        listen 81;
        charset UTF-8;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            expires off;
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
            add_header Pragma "no-cache";
            try_files $uri $uri/ /index.html;
        }

        location /health {
            access_log off;
            return 200 "healthy";
        }


    }
}
