services:
  webserver:
    build:
      context: ..
      dockerfile: docker/webserver/Dockerfile
    image: my-react-vite-app
    pull_policy: never
    container_name: webserver
    ports:
      - "${PORT}:80"
    environment:
      - PORT=${PORT}
      - KC_PORT=${KC_PORT}
      - KC_REALM_NAME=${KC_REALM_NAME}
    volumes:
      - ./webserver/nginx.template.conf:/etc/nginx/nginx.template.conf:ro
      - ./webserver/entrypoint.sh:/docker-entrypoint.sh:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - auth
    networks:
      acad-net:
    entrypoint: ["/bin/sh", "/docker-entrypoint.sh"]


  auth:
    image: quay.io/keycloak/keycloak:19.0.3
    container_name: auth
    volumes:
      - ./keycloak/data:/var/tmp
      - ./keycloak/startup-scripts/init.sh:/init.sh
      - ./keycloak/keycloak.conf:/opt/keycloak/conf/keycloak.conf
      - ./keycloak/customized:/opt/keycloak/themes/customized
    entrypoint: sh -c "/init.sh"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_REALM_NAME: ${KC_REALM_NAME}
      KC_PORT: ${KC_PORT}
      KC_SERVER_URL: ${KC_SERVER_URL}
      KC_PROXY: edge
    ports:
      - "${KC_PORT}:8180"
    depends_on:
      - database-keycloak
    networks:
      acad-net:

  database:
    image: postgres:13
    container_name: database
    restart: always
    ports:
      - "5444:5432"
    volumes:
      - ./postgres/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./postgres/02_setdata.sql:/docker-entrypoint-initdb.d/02_setdata.sql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: ${DB_NAME}

    networks:
      acad-net:

  database-keycloak:
    image: postgres:18
    container_name: database-users
    restart: always
    ports:
      - "5445:5432"
    environment:
      POSTGRES_USER: ${DB_KC_USER}
      POSTGRES_PASSWORD: ${DB_KC_PASSWORD}
      POSTGRES_DB: ${DB_KC_DB}
    networks:
      acad-net:

  minio:
    image: minio/minio:latest
    container_name: minio-storage
    restart: always
    ports:
      - "9000:9000"   # S3 API port
      - "9001:9001"   # Web UI console port
    environment:
      MINIO_ROOT_USER: ${MINIO_USER:-local_admin}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD:-local_password}
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
    networks:
      acad-net:

networks:
  acad-net:

