# Configuration Traefik principale
api:
  dashboard: false
  insecure: true

certificatesResolvers:
  duckdns: # This is your resolver name
    acme:
      storage: "acme.json"
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: duckdns
        disablePropagationCheck: false
        delayBeforeCheck: 60
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

ping: {}

log:
  level: DEBUG
accessLogsFile: /etc/traefik/access.log
